---
version: 2
updates:
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "brucellino"
    assignees:
      - "brucellino"
    labels:
      - terraform
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "actions"
    assignees:
      - "brucellino"
    reviewers:
      - "brucellino"
