name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    strategy:
      matrix:
        example:
          - simple
    name: validate
    env:
      NOMAD_ADDR: http://localhost:4646
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: ${{ github.run_id}}
      TF_VAR_nomad_addr: http://localhost:4646
    runs-on: ubuntu-22.04
    services:
      consul:
        image: hashicorp/consul:1.19.1
        ports:
          - 8500:8500
      nomad:
        image: hashicorp/nomad:1.8.2
        ports:
          - 4646:4646
      vault:
        image: hashicorp/vault:1.17.2
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: ${{ env.VAULT_TOKEN }}
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Get Terraform
        run: |
          curl -fSLO https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_linux_amd64.zip
          unzip -j terraform_1.9.2_linux_amd64.zip terraform
      - name: Init terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} init
      - name: Validate terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} validate
      - name: Init
        run: ./terraform init
      - name: Test
        run: ./terraform test
  release:
    needs:
      - validate
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -D '@semantic-release/commit-analyzer' \
          '@semantic-release/release-notes-generator' \
          '@semantic-release/changelog' \
          'semantic-release-license' \
          '@semantic-release/github'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
