name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  artifact:
    strategy:
      matrix:
        product:
          - nomad
          - terraform
          - vault
          - consul
    runs-on: ubuntu-latest
    env:
      RELEASE_URL: https://api.releases.hashicorp.com
    steps:
      - id: artifact
        name: Get Latest Version of ${{ matrix.product }}
        run: |
          url=$(curl -s "${RELEASE_URL}/v1/releases/${{ matrix.product }}?limit=20&license_class=oss" | jq -r '.[0].builds[] | select (.arch == "amd64" and .os=="linux").url')
          echo ${url}
          echo "${{ matrix.product }}_URL=${url}">>$GITHUB_OUTPUT

  version:
    strategy:
      matrix:
        product:
          - nomad
          - terraform
          - vault
          - consul
    runs-on: ubuntu-latest
    env:
      RELEASE_URL: https://api.releases.hashicorp.com
    steps:
      - id: version
        name: Get Latest Version of ${{ matrix.product }}
        run: |
          v=$(curl -s "${RELEASE_URL}/v1/releases/${{ matrix.product }}?limit=20&license_class=oss" | jq -r '.[0].version')
          echo $v
          echo "${{ matrix.product }}_VERSION=$v" >> $GITHUB_OUTPUT
          cat ${GITHUB_OUTPUT}
  validate:
    needs:
      - version
      - artifact
    strategy:
      matrix:
        example:
          - simple
    name: validate
    env:
      NOMAD_ADDR: http://localhost:4646
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: ${{ github.run_id }}
      TF_VAR_nomad_addr: http://localhost:4646
      VERSIONS: ${GITHUB_OUTPUT}
      TERRAFORM_URL: ${{ needs.artifact.outputs.terraform_URL }}
      TERRAFORM_VERSION: ${{ needs.version.outputs.terraform_VERSION }}
      VAULT_URL: ${{ needs.artifact.outputs.vault_URL }}
      VAULT_VERSION: ${{ needs.version.outputs.vault_VERSION }}
      CONSUL_URL: ${{ needs.artifact.outputs.consul_URL }}
      CONSUL_VERSION: ${{ needs.version.outputs.consul_VERSION }}
    runs-on: ubuntu-22.04
    # services:
    #   consul:
    #     image: hashicorp/consul:${CONSUL_VERSION}
    #     ports:
    #       - 8500:8500
    #   vault:
    #     image: hashicorp/vault:${VAULT_VERSION}
    #     ports:
    #       - 8200:8200
    #     env:
    #       VAULT_DEV_ROOT_TOKEN_ID: ${{ env.VAULT_TOKEN }}
    steps:
      - name: test
        run: echo $GITHUB_OUTPUT
      - name: Checkout code
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Get latest Terraform
        run: |
          curl -fSLO ${terraform_URL}
          unzip -j terraform_${TERRAFORM_VERSION}_linux_amd64.zip terraform
      - name: Init terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} init
      - name: Validate terraform
        run: ./terraform -chdir=examples/${{ matrix.example }} validate
      - name: Init
        run: ./terraform init
      - name: Test
        run: ./terraform test
  release:
    needs:
      - validate
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -D '@semantic-release/commit-analyzer' \
          '@semantic-release/release-notes-generator' \
          '@semantic-release/changelog' \
          'semantic-release-license' \
          '@semantic-release/github'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
